name = "EnergyModelsCO2"
uuid = "84b3f4d7-d799-4a5d-b06c-25c90dcfcad7"
authors = ["Sigmund Eggen Holm <sigmund.holm@sintef.no> and contributors"]
version = "0.7.3"

[deps]
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
SparseVariables = "2749762c-80ed-4b14-8f33-f0736679b02b"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[compat]
EnergyModelsBase = "0.8.1"
JuMP = "1.5"
TimeStruct = "0.9"
julia = "1.10"
SparseVariables = "0.7.3"